In [6]:
import numpy as np

def gradient_descent(X, y, learning_rate, n_iterations, batch_size=1, method='batch'):

    weights=np.zeros(len(X[0]))

    def feed_forward(array, weight):
        return np.dot(array, weight)

    def loss(array, y,w):
        count = 0
        for i, j in zip(array, y):
            count = count + (feed_forward(i, w) - j) ** 2
        return count / (2 * len(y))
    
    def update_batch(weight, array, y):
        w=np.zeros(len(array[0]))
        for i in range(0,len(weight)):
            for j in range(0,len(y)):
                w[i] = w[i] + ((feed_forward(array[j], weight) - y[j]) * array[j][i])
        for i in range (0,len(weight)):
            weight[i]-= learning_rate*2*(w[i]/len(y))
    
    def update_s(weight,array,y):
        
        for i in range (0,len(y)):
            w=np.zeros(len(weight))
            for j in range (0,len(weight)):
                w[j]= (feed_forward(array[i], weight)-y[i])*array[i][j]
            for k in range (0,len(weight)):
                weight[k]=weight[k] -learning_rate*2*(w[k])
    
    def update_mini(weight, array, y,size):
        
        w=np.zeros(len(weight))
        count=0
        
        for i in range (0,len(y)):
            for j in range (0,len(weight)):
                w[j]= w[j]+(feed_forward(array[i], weight)-y[i])*array[i][j]
            count=count+1
            if count==size:
                for k in range (0,len(weight)):
                    weight[k]=weight[k] -learning_rate*2*(w[k]/size)
                w=np.zeros(len(weight))
                count=0
          


    if method == 'batch':
        for i in range (0,n_iterations):
            print(i,end=" ")
            print(loss(X,y,weights))
            update_batch(weights,X,y)
    elif method == 'stochastic':
        for i in range (0,n_iterations):
            print(i,end=" ")
            print(loss(X,y,weights))
            update_s(weights,X,y)
    elif method == 'mini_batch':
        for i in range (0,n_iterations):
            print(i,end=" ")
            print(loss(X,y,weights))
            update_mini(weights,X,y,batch_size)
    return weights
    

In [2]:
# Features (X1, X2, X3)
X = np.array([
    [1, 2, 1],
    [2, 3, 2],
    [3, 4, 3],
    [4, 5, 4],
    [5, 6, 5]
], dtype=float)

# y = 2*X1 + 3*X2 + 4*X3 + 5
y = np.array([21, 32, 43, 54, 65], dtype=float)

In [10]:
gradient_descent(X,y,0.01,20,method='batch')

0 1045.5
1 44.97119999999999
2 4.1343436800000015
3 2.458742833152
4 2.3811942583369756
5 2.36889260392282
6 2.359290021231068
7 2.349834034223879
8 2.3404203404380324
9 2.3310445382401666
10 2.321706303135931
11 2.3124054775832383
12 2.303141911430718
13 2.2939154554043624
14 2.284725960839413
15 2.2755732796670967
16 2.2664572644118746
17 2.257377768188968
18 2.248334644702024
19 2.239327748240769


array([3.66320212, 5.05190488, 3.66320212])

In [11]:
gradient_descent(X,y,0.01,20,method='stochastic')

0 1045.5
1 5.434004720901754
2 3.5798993978268308
3 3.478211064242965
4 3.404549528189384
5 3.3329203358006594
6 3.2628070178469266
7 3.1941688116325415
8 3.126974519649221
9 3.0611937638085727
10 2.996796808128488
11 2.9337545422266134
12 2.8720384681036513
13 2.811620687259957
14 2.752473888084009
15 2.694571333506419
16 2.6378868489135066
17 2.582394810315095
18 2.5280701327613975
19 2.4748882590034373


array([2.88799247, 5.92701541, 2.88799247])

In [12]:
gradient_descent(X,y,0.01,20, batch_size=2,method='mini_batch')

0 1045.5
1 6.930681720000008
2 2.2401452055361117
3 2.2257112548243447
4 2.209539199517599
5 2.19179229373451
6 2.1740628459613482
7 2.156468085665535
8 2.139015113913986
9 2.121703352400383
10 2.1045316978099224
11 2.0874990189578124
12 2.070604191257787
13 2.0538460990476315
14 2.0372236356822233
15 2.020735703472019
16 2.004381213611404
17 1.9881590861067964
18 1.9720682497053978
19 1.956107641824398


array([3.45469316, 5.40885679, 3.45469316])